
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/ruby-rails-sample

    steps:
      - checkout
      - run: 
          name: install dependencies
          command:
           bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)
