
version: 2
jobs:
  build:
    docker:
      - image: rails

    working_directory: ~/ruby-rails-sample

    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
           git clone git@github.com:heroku/ruby-rails-sample.git # or clone your own fork
           cd ruby-rails-sample
           bundle
           bundle exec rake bootstrap
           heroku local
